"""initial

Revision ID: 41a31f316c0b
Revises: 
Create Date: 2024-02-27 12:56:43.468004

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41a31f316c0b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_locations'))
    )
    op.create_table('ratings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('community', sa.Integer(), nullable=True),
    sa.Column('crowds', sa.Integer(), nullable=True),
    sa.Column('safety', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ratings'))
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('_password_hash', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('username', name=op.f('uq_users_username'))
    )
    op.create_table('experiences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('length', sa.String(), nullable=True),
    sa.Column('rating_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], name=op.f('fk_experiences_location_id_locations')),
    sa.ForeignKeyConstraint(['rating_id'], ['ratings.id'], name=op.f('fk_experiences_rating_id_ratings')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_experiences_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_experiences'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('experiences')
    op.drop_table('users')
    op.drop_table('ratings')
    op.drop_table('locations')
    # ### end Alembic commands ###
