"""add constraints/validations to models

Revision ID: 8dcb2ba3e965
Revises: c792cde25ecb
Create Date: 2024-01-13 02:32:21.819597

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8dcb2ba3e965'
down_revision = 'c792cde25ecb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.alter_column('city',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('state',
               existing_type=sa.VARCHAR(),
               nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_users_username'), ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_users_username'), type_='unique')

    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.alter_column('state',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('city',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###
